language: cpp

os: osx
osx_image: xcode9.3

env:
  - FORMULA="qtjsonserializer"
  - FORMULA="qtrestclient"
  - FORMULA="qpmx"
  - FORMULA="qtservice"
  - FORMULA="qtdatasync"
  - FORMULA="qtmvvm"

before_install:
  - brew update
  - brew tap Skycoder42/qt-modules

script:
  - brew install $FORMULA
  - brew test $FORMULA
