language: cpp

os: osx
osx_image: xcode10.2

env:
  - FORMULA=qdep
  - FORMULA=qtjsonserializer
  - FORMULA=qtservice
  - FORMULA=qtautoupdater
  - FORMULA=qtrestclient
  - FORMULA=qtdatasync
  - FORMULA=qtmvvm
  - FORMULA=qtapng

matrix:
  include:
    - os: osx
      env:
        - FORMULA=qtmvvm
        - BREW_ARGS="--without-qtdatasync"
        - TEST_DEPENDS="qtdatasync"  # brew needs this to be installed, even with a different option

before_install:
  - brew update
  - brew tap Skycoder42/qt-modules

script:
# run trice because of strange bug
  - brew install $FORMULA $BREW_ARGS || ./print-logs.sh
  - brew install $FORMULA $BREW_ARGS || ./print-logs.sh
  - brew install $FORMULA $BREW_ARGS || ./print-logs.sh
  - if [ -n "$TEST_DEPENDS" ]; then brew install $TEST_DEPENDS; fi
  - brew test $FORMULA $BREW_ARGS
