name: CI build

on: 
  push:
  schedule:
    - cron:  '0 0 13 * *'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        formula:
          - qdep
          - qtjsonserializer
          - qtservice
          - qtautoupdater
          - qtrestclient
          #- qtdatasync
          - qtapng

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          brew update 
          brew tap Skycoder42/qt-modules
          brew install --only-dependencies ${{matrix.formula}} ${{matrix.install-args}}
      - name: Install formula
        run: brew install ${{matrix.formula}} ${{matrix.install-args}}
      - name: Print error logs
        if: failure()
        run: |
          export LOG_DIR=$HOME/Library/Logs/Homebrew/${{matrix.formula}}/
          ./print-logs.sh
      - name: Test the module
        run: brew test ${{matrix.formula}} ${{matrix.test-args}}
